import { Component} from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {
     // Svg icons
     this.matIconRegistry.addSvgIcon(
      'ic_arrow_select',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_arrow_select.svg')
    );

    this.matIconRegistry.addSvgIcon(
      'ic_refresh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/autorenew-24px.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_Calendar',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_Calendar.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_CapNhatTrangThaiThe',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_CapNhatTrangThaiThe.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_Change',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_Change.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_checkbox',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_checkbox.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_Delete',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_Delete.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_download',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_download.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_dropdown',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_dropdown.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_Duyet',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_Duyet.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_edit',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_edit.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_Lock',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_Lock.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_menu',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_menu.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_minus',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_minus.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_next',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_next.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_plus',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_plus.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QlyChinhSachGia',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_QlyChinhSachGia.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QlyDanhMuc',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_QlyDanhMuc.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QlyHopDong',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_QlyHopDong.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QlyHoSo',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_QlyHoSo.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QlyKhachHang',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_QlyKhachHang.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QlyPhuongTienDacBiet',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        './assets/icons/ic_QlyPhuongTienDacBiet.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'ic_radiobutton',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_radiobutton.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_radiobutton_Select',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_radiobutton_Select.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_settings',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_settings.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_themphuluc',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_themphuluc.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_uncheck',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_uncheck.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_unlink',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_unlink.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_user',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_user.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_xem',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_xem.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_link',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_link.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_file',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_file.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_unLock',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_unLock.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_TiengAnh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_TiengAnh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_TiengViet',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_TiengViet.svg')
    );
    // dungpv_sopen
    this.matIconRegistry.addSvgIcon(
      'menu_HoSoSucKhoe',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_HoSoSucKhoe.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_HoGiaDinh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_HoGiaDinh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_BacSy',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_BacSy.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_KhoKhongXacDinh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_KhoKhongXacDinh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_LienThongDuLieu',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_LienThongDuLieu.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_BaoCaoThongKe',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_BaoCaoThongKe.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_ThietLap',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_ThietLap.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_DanhMuc',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_DanhMuc.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'menu_QuanTriHeThong',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/menu_QuanTriHeThong.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_chevronRight',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_chevronRight.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_LuotLienThongDuLieuKCB',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        './assets/icons/ic_LuotLienThongDuLieuKCB.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'ic_LuotLienThongDuLieuTiemChung',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        './assets/icons/ic_LuotLienThongDuLieuTiemChung.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'ic_LuotLienThongDuLieuNgayHomTruoc',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        './assets/icons/ic_LuotLienThongDuLieuNgayHomTruoc.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'ic_TongSoNhanKhau',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_TongSoNhanKhau.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_HoGiaDinh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_HoGiaDinh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_TreEm',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_TreEm.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_PhuNu',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_PhuNu.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_NguoiCaoTuoi',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_NguoiCaoTuoi.svg')
    );
    // dungpv_sopen
    this.matIconRegistry.addSvgIcon(
      'ic_btn_edit_table',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_edit_table.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_view_table',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_view_table.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_delete_table',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_delete_table.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_face',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_face.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_NgaySinh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_NgaySinh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_gender',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_gender.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_top_left_border',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_top_left_border.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_top_right_border',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_top_right_border.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_bottom_left_border',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_bottom_left_border.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_bottom_right_border',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_bottom_right_border.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'documentAndForm.svg',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/documentAndForm.svg.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_add_profile',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_add_profile.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_image',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_image.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_edit',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_edit.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_update',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_update.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_create',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_create.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_export',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_export.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_add_profile',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_add_profile.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_add_family',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_add_family.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_edit_table',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_edit_table.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_view_table',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_view_table.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_delete_table',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_delete_table.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_add_family1',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_add_family1.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_height',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_height.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_watch',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_watch.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_weight',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_weight.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_bmi',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_bmi.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_blood',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_blood.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_blood_rh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_blood_rh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_btn_health_index',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_btn_health_index.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_vector',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_vector.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_search',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_search.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_view_list',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_view_list.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_edit_list',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_edit_list.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_delete_list',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_delete_list.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_download2',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_download2.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_addPeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_addPeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_add',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_add.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_standardized',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_standardized.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_not_standardized',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_not_standardized.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_add_list_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_add_list_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_cancle_list_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_cancle_list_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_date_list_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_date_list_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_view_list_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_view_list_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_views_list_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_views_list_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_search_adv',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_search_adv.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_export_report',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_export_report.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_export_data',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_export_data.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_img_list_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_img_list_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'change',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/change.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'delete',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/delete.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'detail',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/detail.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_add',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_add.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_download2',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_download2.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_avatar',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_avatar.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_importAvatar',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_importAvatar.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_export',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_export.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_exportData',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_exportData.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_addPeople2',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_addPeople2.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_deletePeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_deletePeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_changePeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_changePeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_detailPeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_detailPeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_loadPeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_loadPeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_donePeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_donePeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_down',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_down.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_detailMedical',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_detailMedical.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_calender',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_calender.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_peopleAdd',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_peopleAdd.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'describe',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/describe.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'calendar',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/calendar.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_search_general',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_search_general.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_book-form',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_book_form.svg')
    );

    this.matIconRegistry.addSvgIcon(
      'ic_uploadImage',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_uploadImage.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_savePeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_savePeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_closePeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_closePeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_searchPeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_searchPeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_add_book_form',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_add_book_form.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_close',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_close.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_save',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_save.svg')
    );

    this.matIconRegistry.addSvgIcon(
      'right',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/right.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_u12',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_u12.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_u18',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_u18.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_stt_chua_duyet',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_stt_chua_duyet.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_stt_da_duyet',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_stt_da_duyet.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_stt_huy',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_stt_huy.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_stt_tu_choi',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_stt_tu_choi.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_stt_het_han',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_stt_het_han.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_openFoder',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_openFoder.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'icon_add_files',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon_add_files.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'icon_openFoder',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon_openFoder.svg')
    ); // TOAN_SOPEN
    this.matIconRegistry.addSvgIcon(
      'lockicon',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon_openFoder.svg')
    );
    // hoaltt6-VT
    this.matIconRegistry.addSvgIcon(
      'ic_success',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_success.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_running',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_running.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_view',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_view.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_error',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_error.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_efficiency',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_efficiency.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_pause',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_pause.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_arrow_back',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_arrow_back.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_hieuLuc',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_hieuLuc.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_tamNgung',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_tamNgung.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_keoXuong',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_keoXuong.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_next',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_next.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_done',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_done.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_tiep_tuc',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_tiep_tuc.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_dollar',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_dollar.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_group_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_group_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_import_people',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_import_people.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_homepage',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_homepage.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_xuong',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_xuong.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_len',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_len.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_setting',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_setting.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_delete_new',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_delete_new.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_blood_new',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_blood_new.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_export_new',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_export_new.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_down_new',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_down_new.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_down_new_new',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_down_new_new.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_people_increase',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_people_increase.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_people_subtract',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_people_subtract.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_arrow_up',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_arrow_up.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_arrow_down',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_arrow_down.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'active-status',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/active-status.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'deactive-status',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/deactive-status.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'icon-cancel',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon-cancel.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'icon-reject',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon-reject.svg'),
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_people_subtract.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_plus_2',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_plus_2.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'icon-menu',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon-menu.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'icon-print',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/icon-print.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_printer',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_printer.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_SoKhamChuaBenh',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_SoKhamChuaBenh.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_QuanLyTuVong',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_QuanLyTuVong.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_KhongLayNhiem',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_KhongLayNhiem.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_LayNhiem',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_LayNhiem.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'toanlock',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/toanlock.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'lokcacoutn2',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/lokcacoutn2.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_time_reload',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_time_reload.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_groupPeople',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_groupPeople.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'mobile',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/mobile.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic-list',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic-list.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic-chart',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic-chart.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_doctor',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_doctor.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_nurse',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_nurse.svg')
    );
    this.matIconRegistry.addSvgIcon(
      'ic_drugs',
      this.domSanitizer.bypassSecurityTrustResourceUrl('./assets/icons/ic_drugs.svg')
    );
  }
}
